### ISSUE TITLE
New Google

### ISSUE THREAD

**Issue by farski** [PRX/prx-podagent#1]
>For noting: the "new" Google Podcasts experience has a useragent of something like Mozilla/5.0 (Linux; Android 8.1.0; Pixel XL Build/OPM2.171019.029; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.109 Mobile Safari/537.36 GSA/8.0.17.21.arm64 - "GSA/" would appear to be the user-agent to search for ('Google Search App'?) - the version number appears to match the version of the Google app that's installed on my phone. Ask your podcast host to add this now to their analytics.

via https://podnews.net/update/google-new-podcasting-trolls-weather

**Comment by cavis** [comment]
TODO: update useragents csv in repo, and find missing stuff.

**Comment by kookster** [comment]
Google Podcasts on Android:` \bGSA\/`
Google Podcasts on smart speakers: `\bGoogleChirp\/`
https://developers.google.com/search/docs/data-types/podcast#analytics

**Comment by kookster** [comment]
I see the `GSA` in there, I think we need to add `GoogleChirp`

**Comment by cavis** [comment]
Note: didn't actually see any `GoogleChirp` in bigquery.  Must be pretty uncommon?

We also split GSA matches between Android and iOS.
