### ISSUE TITLE
Merge in podnews spreadsheet

### ISSUE THREAD

**Issue by cavis** [PRX/prx-podagent#10]
Some good stuff in the [podnews airtable](https://airtable.com/shrh79V7TGie48DAm/tblJSPI6CzPrLXrS3?blocks=hide)

- [ ] Sanity check existing UAs in this repo
- [ ] Add missing UAs
- [ ] Add examples, notes, and url fields to the non-locked yml (and maybe a test that checks each regex against its notes?)

**Comment by jamescridland** [comment]
You're welcome to do this. I'd be happy to help here (though my knowledge of yml is very low).

I'd be keen to merge this work in some form.

**Comment by cavis** [comment]
Thanks @jamescridland.  Out of curiosity ... what format of this database would be most useful to you?  The main file will likely remain yaml, but happy to generate a CSV/HTML or something as an output.

**Comment by jamescridland** [comment]
Probably a CSV, which would allow use of that file in an Amazon Athena
query. I'm not sure how well it would cope with YML (but worthwhile me
looking first).

Anything that lowers barriers to entry would be great, though, so if
there's an auto-generated CSV and/or JSON, I would suspect everyone's happy.
